### ISSUE TITLE
Copying C++ pointers

### ISSUE THREAD

**Issue by grayskripko** [Azure/doAzureParallel#104]
I'm not familiar with C++ code and pointers but I believe this is the root of the next problem.
I want to make a prediction using fitted in an Azure node [lightgbm model](https://github.com/bwilbertz/RLightGBM). I got 
```
Error in lgbm.booster.predict(modelFit$booster.handle, newdata, 0L, modelFit$num_models) : 
  external pointer is not valid
```
The ```lgbm.booster.predict``` function looks this way:
```
function (booster_handle, x, predict_type = 0L, num_used_iterations = -1L) 
{
  .Call("RLightGBM_RLGBM_PredictFromMat", PACKAGE = "RLightGBM", 
    booster_handle, x, predict_type, num_used_iterations)
}
```
And the problem argument
```
> booster_handle
<pointer: (nil)>
```

**Comment by brnleehng** [comment]
Hey Gray,

I was looking into the installation part of the repo. It says 

> Run these lines on Ubuntu 14.04 or later:

We are currently running Centos-OS, which could possibly be the reason why.
I'll investigate more

Thanks
Brian

**Comment by paselem** [comment]
@grayskripko - We have now moved to a docker-based model where the OS is defined by the user (by default though we use Debian 9). That should be compatible with the requirements in repo. Using doAzureParallel v0.6.0 or later, do you still see this issue?

**Comment by paselem** [comment]
@grayskripko we have now moved to docker containers as our host run time and should be able to get around most of these compiler issues by making sure you pull in the right one. By default we use the container image created by the Rocker community which tends to be quite complete. I will close this issue out. Please reopen if you feel this is still an issue.
