### ISSUE TITLE
Spatial Data - Support for NCDF4

### ISSUE THREAD

**Issue by simon-tarr** [Azure/doAzureParallel#105]
Hello, 

Does the Linux DSVM include ncdf4 support? I have raster data in .nc format but my jobs fail with the error:

`Error in { : task 1 failed - 'requireNamespace("ncdf4") is not TRUE'`

Is there a way to provision this using doAzureParallel? If I try and install the R package 'ncdf4' I get the following error (in sdtout.txt):

> Error, nc-config not found or not executable.  This is a script that comes with the
netcdf library, version 4.1-beta2 or later, and must be present for configuration
to succeed. If you installed the netcdf library (and nc-config) in a standard location, nc-config
should be found automatically.  Otherwise, you can specify the full path and name of
the nc-config script by passing the --with-nc-config=/full/path/nc-config argument
flag to the configure script.  For example: ./configure --with-nc-config=/sw/dist/netcdf4/bin/nc-config
 

I suspect I don't actually have access to the ncdf4 configure script because doAzureParallel handles this automatically. Hoping for a workaround! Thank you.

**Comment by paselem** [comment]
I am not familiar with this package, but do you know if ncdf4 is install on the system or not? Based on the error it looks like you may need to install it before trying to use the package. You can take a look at [this](https://github.com/Azure/doAzureParallel/blob/master/docs/30-customize-cluster.md) link to see how to install things on the node before your R code runs. My guess is that you may need to yum install. I found [an article](http://mazamascience.com/WorkingWithData/?p=1429) describing how you can do it with centos 6.x. We use Centos 7, but hopefully it not too much work to adapt.

**Comment by simon-tarr** [comment]
Hello, I'm guessing the libraries aren't part of the default Linux DSVM that doAzureParallel initializes when making a cluster. I'll update the config script to install the appropriate libraries. From looking at the link you provided I'd say this should do the trick - I think it's simply a case of installing ncdf4 before the pool is created.

Many thanks, Simon.

**Comment by simon-tarr** [comment]
**UPDATE**

A quick update for anyone who may need nedf4 support within R in future. The CentOS DSVM used by doAzureParallel already has EPEL installed (which I _believe_ includes the libraries for netCDF files). However, these ncdf4 libraries aren't 'visible' to certain packages (excuse my phrasing!). I added the following code to the cluster config script and everything is now working:

` "commandLine": [
 	"yum --assumeyes install netcdf",
	"yum --assumeyes install netcdf-devel"
    ]
`
