### ISSUE TITLE
[ERROR] 'start task failed' on pool VMs

### ISSUE THREAD

**Issue by huelf** [Azure/doAzureParallel#12]
Hi,

I have a problem with doAzureParallel (0.2.0).

When executing
`pool <- makeCluster("pool_config.json")`
the pool is created, but the DSVMs produce this error: start task failed

stderr.txt shows: `sed: can't read /etc/sudoers: Permission denied`

My pool_config.json is attached. (Had to rename it for upload)
[pool_config_issue.txt](https://github.com/Azure/doAzureParallel/files/887690/pool_config_issue.txt)

I configured the batch and storage account like described here:
https://github.com/Azure/doAzureParallel
Except that I created the storage separately and attached it to the batch account later.

Here's additional information:

> Region. North Europe
> 
> Current cores
> 6
> Operating System
> microsoft-ads linux-data-science-vm linuxdsvm (latest)
> Current nodes
> 3
> VM size
> standard_d2_v2
> Target nodes
> 3
> Allocation state
> Steady
> 
> User Idendity: 
> Task autouser; Admin
> 
> start task:
> /bin/bash -c "set -e; set -o pipefail; sed -i -e 's/Defaults    requiretty.*/ #Defaults    requiretty/g' /etc/sudoers; export PATH=/anaconda/envs/py35/bin:$PATH; sudo env PATH=$PATH pip install --no-dependencies blobxfer;  wait";
> 
> start task failed
> stderr.txt: sed: can't read /etc/sudoers: Permission denied

Regards
Hans

**Comment by huelf** [comment]
After some more tries I found out that

- it works, when the batch account is located in West US
- doesn't work with batch account location North Europe

**Comment by brnleehng** [comment]
I've confirmed that North Europe is not working. I'll investigate more on why North Europe's VMs appear to not install the start task properly.

**Comment by chronicle17** [comment]
Same error if trying to use East US 2.  I'm going to try in West US.

**Comment by brnleehng** [comment]
The issue should be solved. I was able to create a pool and run a foreach job successfully in North Europe and West US.  Issue: We do not need to set up root access since user identity is already run as admin. 

Removed sudo operations:
https://github.com/Azure/rAzureBatch/pull/8
