### ISSUE TITLE
releases/tags more frequently 

### ISSUE THREAD

**Issue by dirkpetersen** [Azure/doAzureParallel#126]
We are managing much of our software stack based on github releases. Would it be possible to add to 
https://github.com/Azure/doAzureParallel/releases a little more frequently, perhaps on a bi-weekly basis ? the change frequency in doAzureParallel is still quite high so more frequent releases would be welcome.

**Comment by paselem** [comment]
Makes a lot of sense. We will look into this and start tagging more often.

**Comment by paselem** [comment]
This is not part of our workflow. Please view the releases page.
