### ISSUE TITLE
Error in if (enableCloudCombine)

### ISSUE THREAD

**Issue by JeffreyNault** [Azure/doAzureParallel#134]
First, thanks for developing this package. Second, my issue is that I receive an error when merging results (I believe). I don't see that this has been logged before, so if it is not an issue with the package, any other suggestion would be helpful. 

Thanks!

> m <- matrix(rnorm(9), 3, 3)
> foreach(i=1:ncol(m), .combine='c') %dopar%   mean(m[,i])
Job Summary: 
Id: job20171001034619
Error in if (enableCloudCombine) { : 
  argument is not interpretable as logical
In addition: Warning message:
In if (enableCloudCombine) { :
  the condition has length > 1 and only the first element will be usedwill be used

**Comment by brnleehng** [comment]
Hey Jeffrey,

We found the issue and merged the solution with this PR #133 
Let me know if you are running into the same issue. 

Thanks!
Brian

**Comment by JeffreyNault** [comment]
Thank you guys. It's working fine. 

Thanks again!

Jeff
