### ISSUE TITLE
issue with caret/parallel, warning & not getting proper fit results 

### ISSUE THREAD

**Issue by rquintino** [Azure/doAzureParallel#140]
Hi been testing the caret parallel sample, but struggling to get it working
(from this https://github.com/Azure/doAzureParallel/blob/master/samples/caret/caret_example.R)

**When running in parallel (using doazure backend), it completes but with abnormal fit results.** 
(can it be something related to version mismatch on caret, randomforest between client and azure servers? how to know/troubleshoot?)

**1-using allowParallel = FALSE, running caret locally, normal metric results** 
(using 5x1 cv)

(rf fit object)
Random Forest 

3451 samples
   6 predictor
   2 classes: 'n', 'y' 

No pre-processing
Resampling: Cross-Validated (5 fold, repeated 1 times) 
Summary of sample sizes: 2761, 2760, 2761, 2761, 2761 
Resampling results:

  **_ROC       Sens       Spec     
  0.911912  0.9526556  0.7573529_**

**2-using allowParallel = TRUE, running random search remotely,** 
(using 5x1 cv)

Job Summary: 
Id: job20171007153351
Job Preparation Status: Package(s) being installed.
Waiting for tasks to complete. . .
  |=============================================| 100%
error calling combine function:
<simpleError in s[[j]]: subscript out of bounds>
Number of errors: 0
**_Warning message:
In nominalTrainWorkflow(x = x, y = y, wts = weights, info = trainInfo,  :
  There were missing values in resampled performance measures._**

(rf fit object)
Random Forest 

3451 samples
   6 predictor
   2 classes: 'n', 'y' 

No pre-processing
Resampling: Cross-Validated (5 fold, repeated 1 times) 
Summary of sample sizes: 2761, 2761, 2761, 2761, 2760 
Resampling results:

  **_ROC  Sens  Spec
  1    NaN   NaN_** 

Tuning parameter 'mtry' was held constant at a value of 6

**Comment by rquintino** [comment]
adding, when I force all caret execution to be remote, results seem to be ok, 
(execute in one remote node only obviously, not in parallel)

I get a warning though, detail below

**_code_**
rf_fit <-foreach(1) %dopar%{
  library(caret)
  fitControl <- trainControl(## 10-fold cross validation
    method = "repeatedcv",
    number = 5,
    repeats = 1,
    classProbs = TRUE,
    summaryFunction = twoClassSummary,
    search = "random",
    **_allowParallel = FALSE)_**
  
  train(
  yesno ~ ., 
  data = training, 
  method = "rf",
  metric = "ROC",
  tuneLength = 30,
  trControl = fitControl)
}

**_warning but fit results seem ok_**

Job Summary: 
Id: job20171007154657
Waiting for tasks to complete. . .
  |========================================================| 100%
**_error calling combine function:
<simpleError: obj$state$numResults <= obj$state$numValues is not TRUE>
Number of errors: 0_**

Random Forest 

3451 samples
   6 predictor
   2 classes: 'n', 'y' 

No pre-processing
Resampling: Cross-Validated (5 fold, repeated 1 times) 
Summary of sample sizes: 2761, 2761, 2761, 2761, 2760 
Resampling results across tuning parameters:

  **_mtry  ROC        Sens       Spec     
  1     0.9138784  0.9502598  0.7529412
  2     0.9160798  0.9397392  0.7772059
  3     0.9136610  0.9311302  0.7838235
  4     0.9130814  0.9244362  0.7926471
  5     0.9101003  0.9158306  0.7977941
  6     0.9085724  0.9062646  0.7985294_**

ROC was used to select the optimal model using  the largest value.
The final value used for the model was mtry = 2.

**Comment by brnleehng** [comment]
Hi I'm currently investigating why our caret sample is not working. I posted an issue on the caret repo. Here's one of the issues I've found. However, your error looks different than the one I'm currently looking at.

https://github.com/topepo/caret/issues/743

**Comment by rquintino** [comment]
Thanks Brian, I have a vague thought that I faced this or similar issue before and it was due to some version mismatch, don't know if R or caret. But I can't remember exactly. :(
Probably makes sense as there's lot more dependence on the R/caret internals.
For now I'm using azuredoparellel as remote job cluster, so I just sent the full code with foreach(1) %dopar%{..} (better way?), and use remote regular registerDoParallel inside if needed.
Know it's not the intended use (not using the task scheduler this way) but working ok for now.
Probably could use the registerDoAzureParallel inside the dopar foreach (sending credentials and clusterinfo)also.

**Comment by HenrikBengtsson** [comment]
I don't think this has to do with the foreach backend (though I might be wrong).  I found that caret does not always export (`.export` argument) all globals needed.  It could be that `allowParallel = TRUE` has mostly been tested using forked processes (when `.export` is non critical).  You can see if you set up a PSOCK cluster (background R sessions), e.g.
```r
library("doParallel")
cl <- parallel::makeCluster(2L)
registerDoParallel(cl)
```
and then run various caret examples, or the example in the top comment - you'll see things like:
```r
> rf_fit <- train(## classification column
+                  yesno ~ ., 
+                  ## dataframe to train on
+                  data = training, 
+                  ## model to use - other models are also available (see caret documentation)
+                  method = "rf",
+                  ## the metric to use for evaluation
+                  metric = "ROC",
+                  ## # of random searches
+                  tuneLength = 30,
+                  ## tuning params
+                  trControl = fitControl)
Error in e$fun(obj, substitute(ex), parent.frame(), e$data) : 
  unable to find variable "optimismBoot"
```

**Comment by brnleehng** [comment]
@rquintino, I ran our caret sample with the latest caret github package (Not the CRAN version). It looks like it's giving the correct results.

@HenrikBengtsson, I agree with there's nothing wrong with the foreach backend. This PR (https://github.com/topepo/caret/pull/748) should export all the needed globals.

**Comment by rquintino** [comment]
hey @brnleehng / @HenrikBengtsson  , currently out of my azure credits for test :) but will test asap. Have been burned very recently by that same install from github and not cran pattern. (not related to doazureparallel). will try as soon as I can but would say that's probably it
thx guys!

**Comment by paselem** [comment]
@rquintino it looks like this issue has been resolve so I'll close it. Please reopen if you feel there is still an issue.

**Comment by stephenbfroehlich** [comment]
I found that doFuture::registerDoFuture() worked as the future package is better about copying environments over to the child processes in a SNOW cluster.
