### ISSUE TITLE
question: load balancing

### ISSUE THREAD

**Issue by rquintino** [Azure/doAzureParallel#141]
Should we expect doazureparallel or azure batch to do some kind of load balancing? 
ex: Some task is running on some nodes, others idle, if a new job is requested will the less used nodes get preference for working on the new one?
thx!

**Comment by paselem** [comment]
Azure Batch uses a 'scheduling policy' to run tasks on the nodes - either spread or pack. By default the tasks are spread across the nodes in the cluster. If a job is scheduled and there are any idle 'slots' to run work on, Batch will immediately schedule the task on that slot. That said, Batch will _never remove_ an existing task if one is already running - all running tasks take preference. Batch will use whatever idle slots are available to start work on any jobs in the queue. 

(Note that by 'slot' I mean a node which has been configured to run N tasks. For example, in doAzureParallel if you set the MaxTasksPerNode property to 2, then each node will have 2 'slots' to run work)

**Comment by rquintino** [comment]
thanks Pablo, good info there
