### ISSUE TITLE
correct way for check job completion & get final result? (non-blocking)

### ISSUE THREAD

**Issue by rquintino** [Azure/doAzureParallel#142]
Not sure of the best way, sometimes the status on getJob would mark all completed but getJobResult would still return error/xml message if immediately called after that. 

Currently using try catch & getJobResult for inferring state/completion but probably not the best way
thx!

 jobResult=tryCatch( getJobResult(jobId),error = function(e) {print(e) })

**Comment by zfengms** [comment]
We will add retry logic in getJobResult so you don't have to do this. Thanks for reporting this problem.
