### ISSUE TITLE
Job Cancellation capability

### ISSUE THREAD

**Issue by rquintino** [Azure/doAzureParallel#143]
Commented on a related thread. 
As we have the non-blocking, would be really useful to be able to cancel running jobs. 

Meantime any workaround using azure batch api?
thx!

**Comment by paselem** [comment]
Hi @rquintino -

Copy/Pasting my comment from other thread (#34):

"Hrm.. Seems like an oversight on our part to not have those exposed. Those functions exist in rAzureBatch though, so you should be able to do something like rAzureBatch::terminateJob(job_id) and rAzureBatch::deleteJob(job_id) as a work around.

Note: If you call deleteJob directly, it will automatically terminate it."

**Comment by rquintino** [comment]
awesome! Thanks @paselem. testing it. Probably makes to expose them through doAzureParallel in case you want to do some extra tasks, or just as abstraction layer, consistency.

**Comment by paselem** [comment]
Resolved with #174
