### ISSUE TITLE
non-blocking/async makeCluster call

### ISSUE THREAD

**Issue by rquintino** [Azure/doAzureParallel#144]
Hi, like the non-blocking/async job management, having that for makeCluster (or any other similar remote jobs) would be great. 
Doesn't make much sense to block current R session work for several minutes just to do nothing imo.
As a workaround, we can probably use future package for that, but it requires new process forks, more resources.

Now an amazing useful scenario would be receiving a notification when finished, while not blocking the r session. Just a thought, probably in the same single threaded R session is not technically possible. (slack notification on request, other?)

**Comment by brnleehng** [comment]
There's a wait flag in the makeCluster function if you don't want to wait for the execution. However, we don't have a way of showing the status of the pool besides using rAzureBatch::getPool(id = "poolId"). 

I've been meaning to look into the future package to support async job management.

That's a good idea, we are working adding a custom merge function after retrieving all the results. With the custom merge function, you can validate all the results then add a slack webhook, https://github.com/hrbrmstr/slackr

**Comment by paselem** [comment]
@rquintino = You can set wait = FALSE in the make cluster call as @brnleehng pointed out above. We have some ideas around setting up events on certain operations for the Batch cluster. For example, you can use email or webhooks today on a cluster resize or cluster create complete event. Would that align with what you're wanting to do?

Some docs to get you started are:
#### Triggering webhooks from Azure
https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/insights-webhooks-alerts

#### Configuring webhooks in Slack
https://api.slack.com/incoming-webhooks

**Comment by zfengms** [comment]
Async cluster creation is now supported by specifying wait=FALSE for makeCluster call: doAzureParallel::makeCluster(clusterFileName, wait=FALSE). getCluster is added to check cluster creation status. #197
