### ISSUE TITLE
Job history being automatically deleted

### ISSUE THREAD

**Issue by toupeiro** [Azure/doAzureParallel#146]
Seems like in the latest version, after the job completes, the job status goes to deleting versus completed.  Therefore, I cannot get any job or task history:

Output as follows:
Job Summary:
Id: job20171011180353

Waiting for tasks to complete. . .
  |======================================================================| 100%
Number of errors: 0
>
>
> getJobResult(20171011180353)
Getting job results...
{xml_document}
<Error>
[1] <Code>ContainerNotFound</Code>
[2] <Message>The specified container does not exist.\nRequestId:8af10182-001e ...
> getJobResult(20171011180353)
Getting job results...
{xml_document}
<Error>
[1] <Code>ContainerNotFound</Code>
[2] <Message>The specified container does not exist.\nRequestId:8af116e8-001e ...
>     replicate(100000, getClosingPrice())
> getJob(20171011180353)

job metadata:
        chunkSize: 1
        enableCloudCombine: TRUE
        packages:

tasks:

$jobId
NULL

$metadata
$metadata$chunkSize
[1] 1

$metadata$enableCloudCombine
[1] "TRUE"

$metadata$packages
[1] ""

$tasks
$tasks$active
NULL

$tasks$running
NULL

$tasks$completed
NULL

$tasks$succeeded
NULL

$tasks$failed
NULL

>

**Comment by brnleehng** [comment]
Hi @toupeiro 

It looks like the job is being run in interactive mode, which means we will handle deleting the job after it's completed. We push all of the logs about the job into Azure Storage, (https://github.com/Azure/doAzureParallel/blob/master/docs/41-managing-storage-via-R.md) and (https://github.com/Azure/doAzureParallel/blob/master/docs/40-troubleshooting.md).

For long running jobs, we will not delete the job after it's completed. For more information, https://github.com/Azure/doAzureParallel/blob/master/docs/31-long-running-job.md

Is the 20171011180353 a string or a integer? The getJobResult should take a string
getJobResult("20171011180353")

**Comment by CharlesCuig** [comment]
Hi @toupeiro 
Do you have any idea on what the error means? I'm trying to do a nested loop such as in https://github.com/Azure/doAzureParallel/blob/master/docs/22-parallelizing-cores.md
but I keep encountering the error:
<Code>ContainerNotFound</Code>
  <Message>The specified container does not exist.
As you had this error as well, do you have any idea on what the reason might be?

Kind regrads
