### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by solvith** [Azure/doAzureParallel#19]
Hi there, 

Thanks for creating this package. It is a fantastic idea. 

I am not too sure if this is the right channel to post it (Please do remove it if you find inappropriate). But i just setup a 8 cores machine and tested a simple function that return (1+1) and it takes about 10 mins.

A monte carlo simulation takes almost a day (and still running) when it could be done 6 hrs on my machine.
I am working for a financial firm in Singapore , and we are willing to test any new grid computing capabilities (and we have azure subscription in our firm).

happy to take this offline, my email is dynamicfusion@gmail.com

Regards
James

**Comment by brnleehng** [comment]
We'll take this offline.
