### ISSUE TITLE
Adjust maxTasksPerNode in an existing cluster

### ISSUE THREAD

**Issue by revodavid** [Azure/doAzureParallel#208]
It would be nice if it were possible to adjust the `maxTasksPerNode` parameter from `cluster.json` without having to tear down and reprovision the cluster. (Also, it would be helpful if the documentation were clearer about the impact of this parameter, to reduce the temptation to toy with it.)

**Comment by paselem** [comment]
@revodavid - thanks for the feedback

Unfortunately the underlying service doesn't allow for this value to be patched. Deleting and recreating the cluster is required. 

With regards to better documentation - yes, you're right, we should do better there. Looking into it.
