### ISSUE TITLE
Error in doAzureParallel install on DSVM in Azure

### ISSUE THREAD

**Issue by brigoodwinan** [Azure/doAzureParallel#216]
Running a linux DSVM in azure... rAzureBatch installs just fine, but when I try to install doAzureParallel, I get the following...

> devtools::install_github("Azure/doAzureParallel")                                       
Downloading GitHub repo Azure/doAzureParallel@master
from URL https://api.github.com/repos/Azure/doAzureParallel/zipball/master
Installing doAzureParallel
Error in data.frame(package = package, installed = installed, available = available,  : 
  row names contain missing values

No idea why.

Please help!

Version information:

> version
               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          3.2                         
year           2016                        
month          10                          
day            31                          
svn rev        71607                       
language       R                           
version.string R version 3.3.2 (2016-10-31)
nickname       Sincere Pumpkin Patch

**Comment by paselem** [comment]
Hello @brigoodwinan ,
Can you please make sure that your devtools  is up to date? Please see #203.

**Comment by zfengms** [comment]
Hi, @brigoodwinan,
Have you tried to update your devtools and did it solve your problem?

**Comment by zfengms** [comment]
@brigoodwinan,

I created 2 unix DSVM (centos and ubunto) based on latest image, they have R 3.4.1 and devtools 1.13.4 and 1.13.3 pre-installed respectively, and I can install doAzureParallel successfully. You have an old version of DSVM provisioned a while ago and seems like it has an out-dated version of devtools package. Here is the version info for my DSVMs:

version
               _
platform       x86_64-pc-linux-gnu
arch           x86_64
os             linux-gnu
system         x86_64, linux-gnu
status
major          3
minor          4.1
year           2017
month          06
day            30
svn rev        72865
language       R
version.string R version 3.4.1 (2017-06-30)
nickname       Single Candle

**Comment by zfengms** [comment]
@brigoodwinan, haven't heard back from you for a while, I assume this issue has been resolved. I'm closing this issue now, if this is not the case, please re-open it or open a new issue. Thanks,
