### ISSUE TITLE
Error in curl::curl_fetch_memory(url, handle = handle) :   Could not resolve host:

### ISSUE THREAD

**Issue by akshaykadidal** [Azure/doAzureParallel#220]
cluster <- makeCluster("cluster.json")
throws this error after i run this.
Error in curl::curl_fetch_memory(url, handle = handle) :   Could not resolve host:

Before submitting a bug please check the following:
- [ ] Start a new R session
- [ ] Check your credentials file
- [ ] Install the latest doAzureParallel package
- [ ] Submit a minimal, reproducible example 
- [ ] run `sessionInfo()`

**Description**

**Instruction to repro the problem if applicable**

**Comment by paselem** [comment]
Hello @akshaykadidal, can you please provide your cluster.json file so we can have a look? Also, did you run setCredentials("credentials.json") command before creating your cluster?

**Comment by brnleehng** [comment]
Closing this. Ensure the url is properly set in the credentials file and run setCredentials before any foreach runs. Feel free to reopen if you are still running into this issue. 

Thanks!
