### ISSUE TITLE
This is not a issue. Can we retrieve the results of a run before the full loop completes?

### ISSUE THREAD

**Issue by akshaykadidal** [Azure/doAzureParallel#221]
Before submitting a bug please check the following:
- [ ] Start a new R session
- [ ] Check your credentials file
- [ ] Install the latest doAzureParallel package
- [ ] Submit a minimal, reproducible example 
- [ ] run `sessionInfo()`

**Description**

**Instruction to repro the problem if applicable**

**Comment by paselem** [comment]
Hi @akshaykadidal 

No, this is currently not possible. All of the results get merged at the end of the job BUT there are way to retrieve intermediate results throughout the run. These are essentially a bunch of small rds files that each loop produces and are later merged together.

Can you provide a bit more information regarding your scenario?

**Comment by paselem** [comment]
Closing. Please let us know if there is anything else you need from the package to support your scenario.

**Comment by akshaykadidal** [comment]
Thank you. I am now writing csvs within the loop to ensure that the results from the job are not lost. My job runs for 2-3 days. So, I cannot afford to re-run the whole thing. This is certainly not an issue.
