### ISSUE TITLE
Error in rAzureBatch::uploadBlob(id, nodeScriptsZip) : The given file does not exist.

### ISSUE THREAD

**Issue by nkaul** [Azure/doAzureParallel#226]
Before submitting a bug please check the following:
- [x] Start a new R session
- [x] Check your credentials file
- [x] Install the latest doAzureParallel package
- [x] Submit a minimal, reproducible example 
- [x] run `sessionInfo()`

**Description**
Similar to:
https://github.com/Azure/doAzureParallel/issues/224

@brnleehng : I have the same issue but I am not on a windows machine. Is there a fix for non-windows users? This is an issue with Redhat / CentOS linux 

```
> closingPrices_p <- foreach(i = 1:100, .combine='c', .options.azure = opt) %dopar% {
+   replicate(100000, getClosingPrice())
+ }
sh: : command not found
Error in rAzureBatch::uploadBlob(id, nodeScriptsZip) : 
  The given file does not exist.
```
```
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS release 6.9 (Final)
...
```

**Reproducibility**
You can follow the basic instructions from the Azure tutorial on any linux system to replicate the issue.
https://docs.microsoft.com/en-us/azure/batch/tutorial-r-doazureparallel

**Comment by paselem** [comment]
@brnleehng looks like this is related to your latest changes.

**Comment by brnleehng** [comment]
@nkaul 

There's an issue with the utils zip function pointing to an external zip program. If it doesn't exist, then this error gets thrown.

I've reverted the latest changes. If you reinstall the doAzureParallel package, you should be good to go. 

Thanks,
Brian

**Comment by paselem** [comment]
#227

**Comment by nkaul** [comment]
@brnleehng : Thanks for fixing this issue.
