### ISSUE TITLE
Unable to install rAzureBatch and doAzureParallel

### ISSUE THREAD

**Issue by itzkunalsatpute** [Azure/doAzureParallel#229]
I am installing rAzureBatch and doAzureParallel from both rStudio and AzureML but both are ending with error

library("devtools")#loaded properly
devtools::install_github("Azure/rAzureBatch")#getting error
Installation failed: schannel: failed to receive handshake, SSL/TLS connection failed

Also if youhave any solutions to directly install to Azure ML then please let me know

**Comment by paselem** [comment]
Hi @itzkunalsatpute - can you give us a bit more info on your environment? Windows/Linux? Local pc/laptop or VM in Azure?
