### ISSUE TITLE
Object 'storageEndpointSuffix' not found

### ISSUE THREAD

**Issue by daanknoope** [Azure/doAzureParallel#242]
**Description**
Commit cea055058c9ac214a1f555f8b05f7e70492f4ae6 introduced the error that the variable `storageEndpointSuffix` could not be found in `credentials.R` since it is incorrectly named `storageSuffix`. This makes it impossible to generate a credentials config using the function `generateCredentialsConfig`.

**Instruction to repro the problem if applicable**
Install the repo and run `generateCredentialsConfig("credentials.json")`.

**Comment by brnleehng** [comment]
Took your PR. It appears we were using the wrong variable name

Thanks!
Brian
