### ISSUE TITLE
"Using Sas Tokens for Private Blobs" was renamed/removed

### ISSUE THREAD

**Issue by amanka** [Azure/doAzureParallel#246]
The samples page references an example that is a dead link.

https://github.com/Azure/doAzureParallel/tree/master/samples

https://github.com/Azure/doAzureParallel/blob/master/samples/resource_files/sas_resource_files_example.R

>Using Sas Tokens for Private Blobs (link)

>This sample walks through using private blobs. The code shows your how to create a Sas token to use when uploading files to your private blob, and then how to use resource files to move your private dataset into your doAzureParallel cluster to execute on.

**Comment by paselem** [comment]
#253

**Comment by paselem** [comment]
#254
