### ISSUE TITLE
Error submitting job: object 'storageCredentials' not found

### ISSUE THREAD

**Issue by dbradnum** [Azure/doAzureParallel#268]
(My first time raising an issue on GitHub - so hope this is all OK!)

I'm trying to get a simple test example working using the latest version of this package, following the Getting Started guide. I can create a pool with no problem, but then receive the following error immediately when I submit a job to it:

```
Error in paste0("/blob/", storageCredentials$name, "/", path, "\n") : 
  object 'storageCredentials' not found 
```

My credentials.json file has been generated via generateCredentialsConfig(), and I've double-checked all the contents.

From a quick look at the package source, I think this may possibly be a problem with something in the rAzureBatch package?
```
> sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server >= 2012 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] doAzureParallel_0.7.0 iterators_1.0.9       foreach_1.4.4        

loaded via a namespace (and not attached):
 [1] httr_1.3.1        rjson_0.2.15      rAzureBatch_0.6.0 R6_2.2.2          tools_3.3.3      
 [6] RCurl_1.95-4.10   curl_2.8.1        codetools_0.2-15  digest_0.6.14     jsonlite_1.5     
[11] mime_0.5          bitops_1.0-6     
```

**Comment by brnleehng** [comment]
@dbradnum 

We added some changes recently for some fixes. We are about to make another release for 0.7.1

Which sample are you using?
Can you try installing the latest doAzureParallel?
``` R
# Latest commit
devtools::install_github("Azure/doAzureParallel", ref = "84aa7c9")
```

Thanks,
Brian

**Comment by dbradnum** [comment]
Hi Brian,

Thanks for the pointers. It turns out that the problem was related to my example (sorry!), since your samples work fine. I'm still a bit puzzled about why my original code doesn't work though, so I'll post a simplified version that should be reproducible, in case there is a bug here somewhere. 

``` r
library(tidyverse)
dummyData = mtcars %>% select(hp,wt)

# transform input values into a list of one or more derived outputs 
getPowerToWt = function(hp,wt){
  return(list(powerToWt = hp/wt))}

# take a dataframe and append calculated columns, using previous function
appendCols = function(data) {
  data %>%
    bind_cols(.,
              pmap_df(.,getPowerToWt))
}

cluster <- makeCluster("cluster.json")
egisterDoAzureParallel(cluster)

# after registering Azure parallel backend, this works as expected
results <- foreach(
  i = seq(1,nrow(dummyData)),
  .combine=rbind,
  .packages=c('tidyverse')) %dopar% {
    appendCols(dummyData[i,])
  }

# ... but this, using an iterator, fails as before
results <- foreach(
  chunk = iter(dummyData,by="row"),
  .combine=rbind,
  .packages=c('tidyverse')) %dopar% {
    appendCols(chunk)
  }

# yet the iterator works fine with a local parallel backend...
doParallel::registerDoParallel()
results <- foreach(
  chunk = iter(dummyData,by="row"),
  .combine=rbind,
  .packages=c('tidyverse')) %dopar% {
    appendCols(chunk)
  }
```

I'm pretty sure when I first had a quick look at doAzureParallel last year, the version using the iterator was also working, so something has changed in the interim. This clearly isn't a big deal though, since I can easily workaround.

**Comment by brnleehng** [comment]
@dbradnum 

I've merged the PR.
If you are still having issues, feel free to reopen issue

Thanks again!
Brian

**Comment by dbradnum** [comment]
Thanks Brian - I've picked up the latest version of the package, and it's all working perfectly. Thanks for the quick turnaround to resolve this.
