### ISSUE TITLE
Automatically load libraries defined in the cluster into the R runtime

### ISSUE THREAD

**Issue by paselem** [Azure/doAzureParallel#28]
Currently, users are forced to load the library within the foreach loop:
```R
library(myLibrary)
```

This should be done automatically for the user.

**Comment by jarvisrob** [comment]
Until is enhancement is incorporated, I suggest that the [manual section on using packages](https://github.com/Azure/doAzureParallel/blob/master/docs/20-package-management.md) is updated to clarify that packages presently need to be loaded with a 'library' call inside the foreach.

**Comment by brnleehng** [comment]
The .packages argument will load the library inside the foreach. The R package management documentation needs some work, it actually doesn't install the packages, only references it.  

foreach(i = 1:3, .packages =c("httr", "ludridate")) %dopar% {}
This is the equivalent of...
foreach(i = 1:3) %dopar% { library("httr") }
