### ISSUE TITLE
Documentation outdated

### ISSUE THREAD

**Issue by ToledoEM** [Azure/doAzureParallel#282]
**Outdated Documentation Persistent Storage**

The documentation about Persistent Storage - Output Files it is not correct since function createContainer do not exist when you load rAzureBatch.  
 
https://github.com/Azure/doAzureParallel/blob/master/docs/72-persistent-storage.md

```
> createContainer(outputFolder)
Error in createContainer(outputFolder) : 
  could not find function "createContainer"
> rAzureBatch::createContainer(outputFolder)
Error: 'createContainer' is not an exported object from 'namespace:rAzureBatch'
> 
```

Also added in here: https://github.com/Azure/rAzureBatch/issues/57

**Comment by brnleehng** [comment]
@ToledoEM 

I'll update the docs

Thanks
Brian

**Comment by ToledoEM** [comment]
Thank you

**Comment by mhelb** [comment]
Still needs to be updated on line 66 here: https://github.com/Azure/doAzureParallel/blob/master/samples/resource_files/resource_files_example.R
