### ISSUE TITLE
Install from GutHub branch

### ISSUE THREAD

**Issue by simon-tarr** [Azure/doAzureParallel#290]
This is more of a general question than an issue but I've searched the documentation and couldn't find an answer. Is it possible to install a particular branch from a GitHub repo? i.e. Not use the master branch. Many thanks.

**Comment by brnleehng** [comment]
Hey @simon-tarr,

To install a particular branch from Github repo in devtools
``` R
devtools::install_github("Azure/doAzureParallel", ref = "feature/branch")
```

Thanks,
Brian

**Comment by simon-tarr** [comment]
Hi Brian, thanks for the reply. I realise now that my question wasn't very clear!

I wanted to install a certain branch when running a loop on Azure. For example:

`test<-foreach(i = 1:10),  github=c("repo/packagename"),  %dopar% { . . . }`

How could I install a different branch instead? I tried `github=c("repo/packagename:mybranch")` and `github=c("repo/packagename@mybranch")` as an educated guess but it doesn't work.

Many thanks.

**Comment by brnleehng** [comment]
Hi Simon,

I see... Yes we don't support the extra commands of devtools install in the parameter. I think one way of doing it is installing on the pool creation level. In the configuration file, you can add some commands  to the pool config. However, this would require some knowledge on Docker. 

Another possibly is running your own Dockerfile with the specific branch installed. Here's a R package that will attempt to create your R dockerfile. https://o2r.info/2017/05/30/containerit-package/

Thanks,
Brian

**Comment by simon-tarr** [comment]
Thanks Brian, I'll give this a go.
