### ISSUE TITLE
Autoscale not autoscaling

### ISSUE THREAD

**Issue by ctlamb** [Azure/doAzureParallel#294]
I have autoscaleFormula=QUEUE, but as the jobs finish, the pool doesn't seem to scale smaller.

my clusterConfig:

```
clusterConfig <- list(
  "name" = "LambRaster",
  "vmSize" = "Standard_D12_v2",
  "maxTasksPerNode" = 1,
  "poolSize" = list(
    "dedicatedNodes" = list(
      "min" = 1,
      "max" = 50
    ),
    "lowPriorityNodes" = list(
      "min" = 0,
      "max" = 0
    ),
    "autoscaleFormula" = "QUEUE"
  ),
  "containerImage" = "rocker/geospatial:latest",
  "rPackages" = list(
    "cran" = list(),
    "github" = list(),
    "bioconductor" = list()
  ),
  "commandLine" = list()
)
```

Nodes are finishing their jobs (50, 4 core nodes in total, 200 cores)
![screen shot 2018-08-08 at 12 31 19 pm](https://user-images.githubusercontent.com/34384805/43856960-30d42ae4-9b07-11e8-8e64-268dae8552df.png)

But my cores count stays consistent at 200 (minus two odd blips..maybe internet cut out..)
![screen shot 2018-08-08 at 12 29 26 pm](https://user-images.githubusercontent.com/34384805/43857160-c1338a94-9b07-11e8-834d-eea1dda07458.png)

**Comment by brnleehng** [comment]
Hi @ctlamb 

Can I get the batch account name, region, and the time that it occurred? If you have some code to reproduce the issue, I'll take a look.

Feel free to email doazureparallel@microsoft.com with this information

Thanks!
Brian

**Comment by brnleehng** [comment]
Working on this offline
