### ISSUE TITLE
Branch Support

### ISSUE THREAD

**Issue by simon-tarr** [Azure/doAzureParallel#301]
Hello, more of a question than an issue but:

Are there any plans for supporting Github package installation from branches other than `master`? I'm currently developing some changes to a package/model that I'm working on...changes that I don't want to make on my working `master` branch.

It would be great to use something like `.github=c("my-username/package-name/test-branch)`. I'm reluctant to continually change master because I have some very long-running models that are accessing code on my master branch. While they're running I can't make any changes to `master` even if I wanted to.

Many thanks.

**Comment by brnleehng** [comment]
Hi Simon,

This is a reasonable request. I'll add Github package installation with references. It should be a relatively easy change since we can follow devtools current pattern for installing R packages with the @ symbol.

``` R
.github=c("username/package-name@ref) 
```
Where ref is the branch/commit/PR # 

Thanks,
Brian

**Comment by simon-tarr** [comment]
Sounds great. I did try this in the first instance actually, thinking that doAzureParallel may already support it. Glad to hear you think it's a good idea, looking forward to this in due course.
