### ISSUE TITLE
 Error in waitForJobPreparation

### ISSUE THREAD

**Issue by simon-tarr** [Azure/doAzureParallel#308]
I booted a cluster this morning to run a few jobs. The jobs that I'm running have not changed in months; the code is exactly the same, the input data are the same and the required packages are the same. Yet when running any new jobs, the job fails after all tasks have been submitted with the error:

```
 Error in waitForJobPreparation(id, data$poolId) : 
  Job 'job20180913072105' unable to install packages. Use the 'getJobFile' function to get more information about job package installation.
```

I did update doAzureParallel yesterday evening after noticing Github branch support has been added (thanks for that!). Could this change have broken anything? I have uninstalled both rAzureBatch and doAzureParallel then reinstalled - still the same error, even with a new R session.

I think, all start tasks are fine - all nodes in the pool are 'idle' prior to submitting any jobs. I am installing packages at the foreach loop stage, not on cluster start up.  Here is are a few minimal examples which may help debug:

This code works. Notice there are no packages (either CRAN or Github) being installed:
```
results<-foreach(i = 1:3) %dopar% {
  results<-1
}

# Edit - this no longer works for me. I get a merge error. Works fine locally if I change %dopar% to %do% however.

```

Added a CRAN package only to install at the foreach level. Error received:
```
results<-foreach(i = 1:3, .packages=c("raster")) %dopar% {
  results<-1
}

```
Added a Github package only to install at the foreach level. Error received:
```
results<-foreach(i = 1:3, github=c("azure/doazureparallel")) %dopar% {
  results<-1
}

```

I've noticed that after the error, all of the nodes on the pool will continue to work for some time (they're highlighted green in the portal). It's like something is still running in the background, despite the error.

Sorry _another_ edit. I've been trying to troubleshoot all morning which explains all the updates.... I ran:
`getClusterFile(cluster, "tvm-1170471534_2-20170829t072146z", "stderr.txt", downloadPath = "pool-errors.txt")` to get the error logs directly after a failed foreach loop. I received the following back:

>  "--2018-09-13 10:47:44--  https://raw.githubusercontent.com/Azure/doAzureParallel/master/inst/startup/cluster_setup.sh\nResolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.36.133\nConnecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.36.133|:443... connected.\nHTTP request sent, awaiting response... 200 OK\nLength: 908 [text/plain]\nSaving to: 'cluster_setup.sh'\n\n     0K                                                       100%  412M=0s\n\n2018-09-13 10:47:44 (412 MB/s) - 'cluster_setup.sh' saved [908/908]\n\n--2018-09-13 10:47:44--  https://raw.githubusercontent.com/Azure/doAzureParallel/master/inst/startup/install_bioconductor.R\nResolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.36.133\nConnecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.36.133|:443... connected.\nHTTP request sent, awaiting response... 200 OK\nLength: 768 [text/plain]\nSaving to: 'install_bioconductor.R'\n\n     0K                                                       100%  366M=0s\n\n2018-09-13 10:47:44 (366 MB/s) - 'install_bioconductor.R' saved [768/768]\n\n--2018-09-13 10:47:44--  https://raw.githubusercontent.com/Azure/doAzureParallel/master/inst/startup/install_custom.R\nResolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.36.133\nConnecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.36.133|:443... connected.\nHTTP request sent, awaiting response... 200 OK\nLength: 1046 (1.0K) [text/plain]\nSaving to: 'install_custom.R'\n\n     0K .                                                     100%  434M=0s\n\n2018-09-13 10:47:44 (434 MB/s) - 'install_custom.R' saved [1046/1046]\n\nE: Unable to locate package linux-image-extra-4.15.0-1023-azure\nE: Couldn't find any package by glob 'linux-image-extra-4.15.0-1023-azure'\nE: Couldn't find any package by regex 'linux-image-extra-4.15.0-1023-azure'\ndebconf: unable to initialize frontend: Dialog\ndebconf: (TERM is not set, so the dialog frontend is not usable.)\ndebconf: falling back to frontend: Readline\ndebconf: unable to initialize frontend: Readline\ndebconf: (This frontend requires a controlling tty.)\ndebconf: falling back to frontend: Teletype\ndpkg-preconfigure: unable to re-open stdin: \ndebconf: unable to initialize frontend: Dialog\ndebconf: (TERM is not set, so the dialog frontend is not usable.)\ndebconf: falling back to frontend: Readline\ndebconf: unable to initialize frontend: Readline\ndebconf: (This frontend requires a controlling tty.)\ndebconf: falling back to frontend: Teletype\ndpkg-preconfigure: unable to re-open stdin: \n"

I'm confused!

**Comment by simon-tarr** [comment]
Here are a few stderr.txt files that we're generated.

With .packages not included as an argument:

```
> running
>   '/usr/local/lib/R/bin/R --slave --no-restore --no-save --no-environ --no-restore --no-site-file --file=/mnt/batch/tasks/workitems/job20180913120355/job-1/jobpreparation/wd/worker.R --args 10 10 0 stop'
> 
> Warning: namespace ‘foreach’ is not available and has been replaced
> by .GlobalEnv when processing object 
```

This fails and I get the error: `An error has occurred in the merge task of the job 'job20180913120355'. Error handling is set to 'stop' and has proceeded to terminate the job. The user will have to handle deleting the job. If this is not the correct behavior, change the errorhandling property to 'pass'  or 'remove' in the foreach object. Use the 'getJobFile' function to obtain the logs. For more information about getting job logs, follow this link: https://github.com/Azure/doAzureParallel/blob/master/docs/40-troubleshooting.md#viewing-files-directly-from-compute-node`

With .packages = c("tidyverse") being included:

```
running
  '/usr/local/lib/R/bin/R --slave --no-restore --no-save --no-environ --no-restore --no-site-file --file=/mnt/batch/tasks/workitems/job20180913120652/job-1/jobpreparation/wd/worker.R --args 5 5 0 stop'

Warning: namespace ‘foreach’ is not available and has been replaced
by .GlobalEnv when processing object ‘’
── Attaching packages ─────────────────────────────────────── tidyverse 1.2.1 ──
✔ ggplot2 3.0.0     ✔ purrr   0.2.5
✔ tibble  1.4.2     ✔ dplyr   0.7.6
✔ tidyr   0.8.1     ✔ stringr 1.3.1
✔ readr   1.1.1     ✔ forcats 0.3.0
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

```
After this runs I get the error: `Error in waitForJobPreparation(id, data$poolId) : 
  Job 'job20180913120652' unable to install packages. Use the 'getJobFile' function to get more information about job package installation.`

**Comment by simon-tarr** [comment]
Some more information after (yet more!) testing. I've found that it could be something to do with the WAIT parameter. For example, the following code will return the correct result:

```
opt <- list(job = 'testjob1', wait = FALSE)
job_id_2 <- foreach(i = 1:10, .options.azure = opt) %dopar% {  job_id_2<-1}
```

However when WAIT=TRUE I get the same merge task error that I have documented in the previous two comments to this post.

**Comment by brnleehng** [comment]
Hi Simon,

I've ran doAzureParallel with the stable branch and the previous commits.

Using the setAutoDeleteJob function
``` R
setAutoDeleteJob(FALSE)
```

I see that the merge results on the node has the correct results. I'm thinking that the waitForJobsToComplete function is not producing the correct count of tasks status. 
Will be doing further investigation.

Thanks,
Brian

**Comment by simon-tarr** [comment]
Hi Brian, 

I also tried going back to the stable branch but couldn't get it to work - the same combination of errors as I've detailed above. I've tried so many different things today to get this working that it's possible I did something wrong when rolling back, however. 

Please let me know if you need any more information from me regarding this issue - I have a deadline approaching soon and really need to get cracking on this analysis I'm running as it's going to take several weeks, even in the cloud.

Thanks in advance for your help.

Cheers
Simon

**Comment by brnleehng** [comment]
Hi Simon,

During our latest service deployment, the service returned the merge task's execution info result enum as a lowercase 'success'. With R being case sensitive, we weren't able to catch it. 

The PR #310  is out. 

Thanks,
Brian

**Comment by simon-tarr** [comment]
Hi Brian,

Thanks very much for the speedy fix. I've downloaded your latest patch and everything is now working as expected.

Cheers
Simon
