### ISSUE TITLE
Link to sample code in "21-distributing-data.md" seems to be broken.

### ISSUE THREAD

**Issue by yueguoguo** [Azure/doAzureParallel#31]

**Comment by yueguoguo** [comment]
Pointing to "https://github.com/Azure/doAzureParallel/blob/release/samples/resource_files_example.R"

**Comment by jiata** [comment]
thanks for spotting this. resolved in this commit: https://github.com/Azure/doAzureParallel/commit/3f5dc8fac0ff3c56889535d9f4141d9403f93ea3
