### ISSUE TITLE
GetJobResults('jobName') returns the raw binary result

### ISSUE THREAD

**Issue by paselem** [Azure/doAzureParallel#32]
When calling getJobResult('foojob') for a long running job, the result is a binary blob like:

[1] 1f 8b 08 00 00 00 00 00 00 03 14 9d 77 38 d5 ef 1f c6 8d 4a 4a 9a 48 12 45 24 92 32 92 8a 5b 4a a4 cc ac
  [36] a2 14 0a d9 eb 38 8b b3 cf e1 d8 7b 14 85 10 95 24 4d 2a a3 21 45 52 9a 44 2a eb 8b ca 28 a5 fa 7d 7e 7f
...

The returned result should be the same object type as if running a regular loop

blocking_job <- foreach(...) %dopar% {}
non_blocking_job <- foreach(..., .azure.options.wait = FALSE) %dopar {}

The results should be such taht blocking_job == non_blocking_job

**Comment by brnleehng** [comment]
Workaround:
bin_results <= doAzureParallel::getJobResults(jobId= “test-job”)
 
# Create a temp file for the results
tempFile <- tempfile("getJobResult", fileext = ".rds")
writeBin(bin_results, tempFile)
 
# Deserialize the file with the binary results as a R object
results <- readRDS(tempFile)

**Comment by zfengms** [comment]
#130
