### ISSUE TITLE
GitHub - Unable to install packages

### ISSUE THREAD

**Issue by simon-tarr** [Azure/doAzureParallel#323]
This morning I've been trying to boot around 12 pools. After booting I will often get the following error upon job submission:

```
Error in waitForJobPreparation(id, data$poolId) : 
  Job 'job20181109094012' unable to install packages. Use the 'getJobFile' function to get more information about job package installation. 
```

When this error occurs, I close R to restart the session, and boot the pool again. Sometimes after booting, all jobs will submit and run and I will never get the error. Of the 12 concurrent sessions that I'm running today I would say about 6-8 of them will keep stopping with the above error.

This issue has been most noticable to me since yesterday afternoon. Prior to this I would very rarely get this error. My workflow hasn't changed recently so all packages have worked fine in the past. I've added no new GitHub or CRAN packages to my workflow and all work as expected (so it's not an issue with the packages or package-hosting services; as I say, some pools will run fine). All pools are 8 * E64sV3 VMs.

I'm running the latest version of doAzureParallel and rAzureBatch.

**Comment by simon-tarr** [comment]
After some more time I've found that pretty much all but one of the pools I need to run today are "stable". By stable I mean that only one instance of R and its associated pool is currently running _without_ the above error. 

I've started countless pools today and every one since about 9.30am has thrown this error. 

I've checked sterr.txt on startup and there appear to be no errors. I am installing packages at the foreach loop stage, not at cluster boot (I've never been able to run my jobs when installing packages on cluster start)

**Comment by brnleehng** [comment]
When you mean boot the pool again, you mean creating a new pool?
Can I get a copy of your cluster config file?
Do you also have a copy of the job preparation error logs?

**Comment by simon-tarr** [comment]
I spoke too soon! After submitting the above reply I've checked on the status of the jobs and the package installation error is back in full force again.

I've copied below my cluster config file which I've generated programatically.

```
   clusterConfig <- list(

      "name" = "cluster",
      "vmSize" = "Standard_E64s_v3",
      "maxTasksPerNode" = 64,
      "poolSize" = list(
        "dedicatedNodes" = list(
          "min" = 0,
          "max" = 0
        ),
        "lowPriorityNodes" = list(
          "min" = 8,
          "max" = 8
        ),
        "autoscaleFormula" = "QUEUE"
      ),
      "containerImage" = "rocker/geospatial:latest",
      "rPackages" = list(
        "cran" = list(),
        "github" = list(),
        "bioconductor" = list()
      ),
      "commandLine" = list()
    )
```

Is there documentation available to find and copy the job preparation error logs?

**Comment by simon-tarr** [comment]
A little extra information to supplement the above:

The error isn't always occuring after submitting tasks in the first job after pool creation (as I mentioned previously). I've tried again this morning to run jobs and was able to run 4 complete jobs after pool creation. The fifth job failed with the aforementioned error.

I think it's likely that there's nothing wrong with my code, otherwise there would never be an instance of a job completing. There must be some problem with either the VM type or with the job submission process, no? I noticed that some new changes were commited to doAzureParallel master 5 days ago - right when I started having these issues ([this commit](https://github.com/Azure/doAzureParallel/commit/975d68e47bcd594128b26956fb414cb6d44285d1)) which, according to the changelog, suggests there have been changes to the job submission process. Is it possible something has gone awry here?

This could be a red herring as I uninstalled both doAzureParallel and rAzureBatch (which were running the latest commit to master) and installed the latest stable release using `install_github("azure/doazureparallel@v0.7.2")` and still get the error. Either way, it seems like a coincidence.

Very confused at this point!

**Comment by simon-tarr** [comment]
Still getting the error (Sunday evening). I've set setAutoDeleteJob(FALSE) in order to track down the job preparation files. In this particular failure, 4 jobs ran successfully before the package installation error. The job state for these four is 'completed'. The fifth job (which has failed) has a status of 'active'.

I have gone into my batch account, navigated to jobs and then to job which failed. Under 'general' I have selected 'preparation tasks'. It looks like this:

![screenshot from 2018-11-11 17-04-05](https://user-images.githubusercontent.com/27423094/48315892-db9a9000-e5d3-11e8-949a-c2d0c0f95f0d.png)

I've then clicked on one of the nodes for more information and have included the screenshot of one of them. Note though that it's the same for all nodes in the pool:

![screenshot from 2018-11-11 17-00-20](https://user-images.githubusercontent.com/27423094/48315898-07b61100-e5d4-11e8-95d4-61d81c99f646.png)

This is the stdout.txt file associated with the failed job which mentions GitHub. I am trying to install a package from Github but it's not a private repo...it's publicly available at github.com/simon-tarr/nichemapr:

```
Installing R Packages & Downloading Resource Files
Error getting parent environment: HTTP error 403.
  API rate limit exceeded for 13.94.129.158. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

  Rate limit remaining: 0/60
  Rate limit reset at: 2018-11-11 17:32:43 UTC

  To increase your GitHub API rate limit
  - Use `usethis::browse_github_pat()` to create a Personal Access Token.
  - Use `usethis::edit_r_environ()` and add the token as `GITHUB_PAT`.
```
Is it possible that GitHub made a change at some point during the week, limiting the number of times a public package can be access and installed? As I say, nothing in my analysis has changed, I started getting the error Wednesday afternoon.

**Comment by simon-tarr** [comment]
Sorry for another message but using this thread as a means to document every troubleshooting step I've taken over the weekend.

I tried increasing the API limit given the message in the above post - this hasn't worked. I then tried creating a docker image from the doAzureParallel documentation here on Github. I can get it working locally (i.e. all the correct packages will install and load) and I can also get doAzureParallel to download the image. However, my code won't run and I ran out of time yesterday evening to troubleshoot the problem.

Although I am attempting to get things working via a different avenue, I would still like to troubleshoot the original problem of the package installation error, now seemingly an issue with Github rate limits.

Thanks,
Simon

**Comment by brnleehng** [comment]
I'll add some documentation on the github API limit. 
How many nodes are in each pool? So I can hit these limits

Thanks,
Brian

**Comment by simon-tarr** [comment]
I always run 8 x VMs for my current workflow.

**Comment by simon-tarr** [comment]
Do you think there has been a change to the GitHub API?

As I say, I've been running loads of 8 x VM pools over the previous few weeks and never had a problem with packages being installed until around 9 days ago. Nothing has changed with the doAzureParallel package or my workflow so I'm assuming it must be something GitHub's end.

**Comment by brnleehng** [comment]
Will be closing this. Github's API Rate limit decreased, must use the PAT token or create your own docker image
