### ISSUE TITLE
libpaths duplicated twice

### ISSUE THREAD

**Issue by simon-tarr** [Azure/doAzureParallel#324]
I've been having issues with GitHub limiting the number of API calls to the service, preventing me from installing GitHub packages on every iteration of a foreach loop within doAzureParallel (see #323).

In an attempt to sidestep this issue, I decided to create a custom Docker image, using the documentation provided [here](https://github.com/Azure/doAzureParallel/blob/2b8f388dc476a3a51aa71c3ab1165d080ad08fe8/docs/33-building-containers.md). I have been successful in creating an image and I can successfully load the GitHub package required for my analysis locally. I have also been successful in pushing it to Docker hub (it can be found [here](https://hub.docker.com/r/arcalis/nichemapr/)) and getting a cluster to boot with my image.

The problem arises, however, when I attempt to load the same GitHub-installed packge into my session on Azure (using `library(NicheMapR)`). If I use a simple example, just to load the package:

```
# Generate cluster config file with custom docker image
    clusterConfig <- list(

      "name" = "test_cluster
      "vmSize" = "Standard_E64s_v3",
      "maxTasksPerNode" = 64,
      "poolSize" = list(
        "dedicatedNodes" = list(
          "min" = 0,
          "max" = 0
        ),
        "lowPriorityNodes" = list(
          "min" = 8,
          "max" = 8
        ),
        "autoscaleFormula" = "QUEUE"
      ),
      "containerImage" = "arcalis/nichemapr",
      "rPackages" = list(
        "cran" = list(),
        "github" = list(),
        "bioconductor" = list()
      ),
      "commandLine" = list()
    )

    cluster <<- doAzureParallel::makeCluster(clusterConfig, resourceFiles = resource_files)

test <- foreach(i = 1:5, .errorhandling = 'pass') %dopar% {

  library(NicheMapR)
  sessionInfo()
  
  }
```

I get the following error for each iteration of the loop: 
```
$`1`
<simpleError: package or namespace load failed for â€˜NicheMapRâ€™:
 .onLoad failed in loadNamespace() for 'NicheMapR', details:
  call: dyn.load(micro_lib)
  error: unable to load shared object '/mnt/batch/tasks/workitems/job20181112134610/job-1/jobpreparation/wd/mnt/batch/tasks/workitems/job20181112134610/job-1/jobpreparation/wd/NicheMapR/libs/linux/MICROCLIMATE.so':
  /mnt/batch/tasks/workitems/job20181112134610/job-1/jobpreparation/wd/mnt/batch/tasks/workitems/job20181112134610/job-1/jobpreparation/wd/NicheMapR/libs/linux/MICROCLIMATE.so: cannot open shared object file: No such file or directory>

```

You'll notice that the path string` /mnt/batch/tasks/workitems/job20181112134610/job-1/jobpreparation/wd/` is repeated twice. I've scoured the NicheMapR package code for many hours in my forked copy (simon-tarr/nichemapr@libpath-updates) and can't see anywhere the first entry in .libpaths is duplicated twice, which would result in the above duplication.

It's probably a NicheMapR issue, in which case, I obviously expect no support. However, I would be grateful if you could share any information from the doAzureParallel side of things which might shed some light on what's going on here.

Thanks,
Simon

**Comment by simon-tarr** [comment]
I believe this was a coding error on my part which was resulting in `/mnt/batch/tasks/workitems/job20181112134610/job-1/jobpreparation/wd/` being duplicated.

After sorting the faulty code, however, I still get the error (i.e. the libpath isn't duplicated):

`<simpleError: package or namespace load failed for â€˜NicheMapRâ€™:
 .onLoad failed in loadNamespace() for 'NicheMapR', details:
  call: dyn.load(micro_lib)
  error: unable to load shared object '/mnt/batch/tasks/workitems/job20181112134610/job-1/jobpreparation/wd/NicheMapR/libs/linux/MICROCLIMATE.so':
  /mnt/batch/tasks/workitems/job20181112134610/job-1/jobpreparation/wd/NicheMapR/libs/linux/MICROCLIMATE.so: cannot open shared object file: No such file or directory>`

**Comment by brnleehng** [comment]
Hi Simon, 

I'll start a new pool with this cluster configuration file. 

If you are installing the R packages from the cluster configuration file, the packages are installed in the $AZ_BATCH_NODE_SHARED_DIR/shared/R/packages directory.

However, if you are installing R packages inside the docker image, it's installed in the default R package path.

Can I see the commands within your dockerfile? I think the solution is to find the path of the R package installation within your dockerfile. Then add a default libPath in your Rprofile file as a command in the dockerfile. 

Thanks,
Brian

**Comment by simon-tarr** [comment]
Hi Brian,

Thanks for getting back to me. Here's a copy of my dockerfile:

```
# Pulls latest geospatial rocker image
FROM rocker/geospatial:latest

# Install any dependencies required for the R packages
RUN  apt-get update \
  && apt-get install -y --no-install-recommends \
  libxml2-dev \
  libcurl4-openssl-dev \
  libssl-dev

# Install the R Packages from CRAN
RUN Rscript -e 'install.packages(c("foreach"))'
RUN Rscript -e 'devtools::install_github(c("simon-tarr/NicheMapR"))'
```

Cheers,
SImon

**Comment by brnleehng** [comment]
Hi Simon,

I found that the R packages are installing on the default installation directory. (/usr/local/lib/R/site-library). 

Here's a current workaround. You can delete all the current libPaths with the libPath of NicheMapR. 
``` R
test <- foreach(i = 1:1, .errorhandling = 'pass') %dopar% {
  .libPaths("/usr/local/lib/R/site-library")
  library(NicheMapR)
  sessionInfo()
}
```

Thanks
Brian

**Comment by simon-tarr** [comment]
Hi Brian,

Thanks so much for the workaround. It's getting quite late here in the UK for me to try this but I'll give it a go first thing in the morning. 

Just one thing; could you clarify what you mean when you say "You can delete all the current libPaths with the libPath of NicheMapR"? Does that mean that the line `.libPaths("/usr/local/lib/R/site-library")` will overwrite the packages attempt to look elsewhere for the necessary files?

I only have a few hundred models left to run so anything that can get me across the line over the next few days will be a lifesaver! I'll report back soon and let you know how I get on.

Cheers
Simon

**Comment by simon-tarr** [comment]
Closing this issue because the .libpath workaround is allowing the package to find the necessary files for successful package installation.

**Comment by brnleehng** [comment]
For clarification, the R session will only look at that path: (/usr/local/lib/R/site-library). So if you are using any R packages from the pool cluster configuration or job preparation, the R session will not find them.

However, if you prebake all your R packages inside your docker image at /usrs/local/lib/R/site-library, you'll be fine
