### ISSUE TITLE
Can't access task logs with getJobFile()

### ISSUE THREAD

**Issue by angusrtaylor** [Azure/doAzureParallel#332]
Before submitting a bug please check the following:
- [x ] Start a new R session
- [x ] Check your credentials file
- [x ] Install the latest doAzureParallel package
- [ ] Submit a minimal, reproducible example 
- [ ] run `sessionInfo()`

**Description**

When a job fails, log files are generated under /<jobID>/logs in blob storage. I cannot find a way to access these files from the R session using getJobFile(). It seems to be because the naming convention for these files differs from that of stdout, stderr and results files. E.g. stdout files are output as

/<jobID>/stdout/1-stdout.txt
/<jobID>/stdout/2-stdout.txt
/<jobID>/stdout/3-stdout.txt
...
which can be retrieved with getJobFile("<jobID>", "<taskID>", "stdout.txt"). However, log files are output as:
/<jobID>/logs/1.txt
/<jobID>/logs/2.txt
/<jobID>/logs/3.txt
...

There doesn't seem to be a way of extracting these files. E.g. the following do not work:
getJobFile("<jobID>", "<taskID>", "logs")
getJobFile("<jobID>", "<taskID>", ".txt")
getJobFile("<jobID>", "<taskID>", "logs.txt")

**Comment by brnleehng** [comment]
I'll take a look at this and will get back to you.

Thanks!
Brian

**Comment by brnleehng** [comment]
Are you using `SetAutoDeleteJob` flag?
The issue could be that SetAutoDeleteJob is set to `TRUE` which means the files under the job have already been deleted. 

You can use the doAzureParallel's Storage APIs to get the task logs from storage (https://github.com/Azure/doAzureParallel/blob/6d14d4522b1ff4218f19549b89dea6419a230a53/docs/73-managing-storage.md)

``` R
files <- listStorageFiles("job20181129064540", prefix = "logs")
View(files)

cat(getStorageFile("job20181129064540", "logs/3.txt"))
```

The getJobFile function seems to not be extracting the Batch response correctly. I'll get a fix in for this.

**Comment by angusrtaylor** [comment]
The log files are generating correctly and I can view them in Storage Explorer/Portal. The problem is that it seems impossible to retrieve them using getJobFile. Thanks for the listStorageFiles workaround.

**Comment by brnleehng** [comment]
Hi @angusrtaylor 

Can you verify that the following function?
``` R
getJobFile("job20181205211122", "1", "wd/1.txt")
getJobFile("job20181205211122", "1", "stderr.txt")
getJobFile("job20181205211122", "1", "stdout.txt")
```

There's a couple things we need for fixing. 

I'll add a node list files directory API for doAzureParallel so users know how Batch structures its files.

**Comment by angusrtaylor** [comment]
Thanks, yes all those functions work for me.
