### ISSUE TITLE
Batch Insights support for doAzureParallel

### ISSUE THREAD

**Issue by ctlamb** [Azure/doAzureParallel#335]
Trying to get batch-insights going for my mac. I have all the keys ready, following the steps provided. But I don't see a BATCH_INSIGHTS_DOWNLOAD_URL download URL for mac, and I'm unclear where I provide the start task info?

**Comment by brnleehng** [comment]
Hi @ctlamb 

I've added a PR for Batch Insights support.

For installing this branch
``` R
devtools::install_github("Azure/doAzureParallel", ref = "feature/app-insights")
```

**Comment by ctlamb** [comment]
Fantastic, much appreciated!
