### ISSUE TITLE
makeCluster is timing out with allocation failed error

### ISSUE THREAD

**Issue by WagdyIshac** [Azure/doAzureParallel#349]
after the last update, the makeCluster() with the same configuration isn't creating the cluster
it times out then sending the error 
 Code: AllocationFailed - Message: Desired number of low priority nodes could not be allocated 

I'm using low priority nodes F16s and tried in West & North Europe.
also using my github image wegz/r-base-hitandrun 
below is the session info

R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] devtools_1.12.0       doAzureParallel_0.7.2 iterators_1.0.8       foreach_1.4.3         RevoUtilsMath_10.0.0  RevoUtils_10.0.2      RevoMods_10.0.0       MicrosoftML_1.0.0     mrsdeploy_1.0         RevoScaleR_9.0.1      lattice_0.20-34       rpart_4.1-10         

loaded via a namespace (and not attached):
 [1] codetools_0.2-15       CompatibilityAPI_1.1.0 rAzureBatch_0.6.2      withr_1.0.2            digest_0.6.10          mime_0.5               bitops_1.0-6           grid_3.3.2             R6_2.2.0               jsonlite_1.1           git2r_0.15.0           httr_1.2.1             curl_2.2               rjson_0.2.15          
[15] tools_3.3.2            RCurl_1.95-4.8         memoise_1.0.0          rtvs_1.0.0.0           mrupdate_1.0.0

**Comment by brnleehng** [comment]
Hi @WagdyIshac 

Are you reaching your core quota limits?

Thanks,
Brian

**Comment by WagdyIshac** [comment]
No, when I reverted back to @stable I can create clusters, but the @master isn't working and now giving the error 
Reason: The property 'containerConfiguration' does not exist on type 'Microsoft.Azure.Batch.Protocol.Entities.VirtualMachineConfiguration'. Make sure to only use property names that are defined by the type.
I use the same config file generated by the tool

**Comment by WagdyIshac** [comment]
Hi @brnleehng 
digging deep for a reason the $addpool function in cluster.R is crashing because of line 245
` response <- BatchUtilitiesOperations$addPool(
      pool = poolConfig,
      packages = packages,
      environmentSettings = environmentSettings,
      resourceFiles = resourceFiles,
      commandLine = commandLine,
      networkConfiguration = networkConfiguration,
      containerConfiguration = containerConfiguration,
      applicationInsights = config$applicationInsights
    )`
it's crashing on line 245 which is
`containerConfiguration = containerConfiguration`

**Comment by brnleehng** [comment]
ARM templates has a different REST api versioning. You should follow the Batch Service REST version docs. 

In 2017-09-01.6.0 API, containerConfiguration property is added to VirtualMachineConfiguration. 
https://docs.microsoft.com/en-us/rest/api/batchservice/batch-service-rest-api-versioning#version-2017-09-0160

The version of rAzureBatch (v0.6.2) uses **2018-03-01.6.1**.. In stable (rAzureBatch v0.6.1) is using API version **2-17-06-01.5.1**.. 
When you are installing doAzureParallel via **master**, it seems to me that somehow rAzureBatch v0.6.1 is still being loaded.. 

Can you install rAzureBatch v0.6.2 separately from doAzureParallel and restart your RStudio session?
Can you also share your cluster config?

Thanks,
Brian

**Comment by WagdyIshac** [comment]
Switching from VS to R studio and starting on a clean environment the process run smoothly with no issues, I believe the issue was that somehow VS is loading somehow v0.6.1 regardless of loading it again and re-loading it to the session
Thank you for your help. I've attached the cluster config for reference

[clusterHPC.txt](https://github.com/Azure/doAzureParallel/files/2890563/clusterHPC.txt)

**Comment by brnleehng** [comment]
Thanks for your investigation
