### ISSUE TITLE
Maintaining R objects in workers memory possible? avoid data transfer?

### ISSUE THREAD

**Issue by rquintino** [Azure/doAzureParallel#35]
Is it possible to reuse remote R objects between job requests? and avoid the data transfer?
ex: transfer a data.frame only the first time is needed? or manually when I need to refresh for some reason.

ex: this always takes around >100secs on low priority 3 Standard_D5_v2 nodes, 16 max tasks
would say it's always sending the data for the job, would be great to send once and pin in remote workers memory/session somehow.

my_data_set <- iris[sample(150,1e6,replace = TRUE),]
system.time(results <- foreach(i = 1:number_of_iterations) %dopar% {
  c((system('hostname',intern=T)),NROW(my_data_set))
})
results

[1] "Job Summary: "
[1] "Id: job20170629182458"
[1] "Waiting for tasks to complete. . ."
  |=========================================================| 100%[1] "Number of errors: 0"
   user  system elapsed 
   **_5.52    0.19  115.11_** 
There were 14 warnings (use warnings() to see them)

**Comment by paselem** [comment]
This is a great observation/feature request. We are looking into a feature to pre-load an environment into the job so you only need to generate it once, upload it to storage and ask us to re-hydrate it to the local R session. It should significantly benefit transfer times since it only needs to hydrate from storage.

**Comment by paselem** [comment]
You can load the data into storage once, and use resource files to download the data into each node when the cluster sets up. This will prevent you from having to push it up with every job (as part of the job environment) and you can load it directly from disk which should have much better performance between jobs.

You can find more information here: https://github.com/Azure/doAzureParallel/blob/master/docs/21-distributing-data.md
