### ISSUE TITLE
Is a storageAccount mandatory?

### ISSUE THREAD

**Issue by BastienFR** [Azure/doAzureParallel#350]
Couple of months ago, creating a batchAccount on Azure Batch needed to link a storageAccount (as shown in the not updated tutorial: https://docs.microsoft.com/en-us/azure/batch/quick-create-portal).  

However, recently, linking a storageAccount is optionnal (PS from my portal):

![image](https://user-images.githubusercontent.com/10979480/53018974-b498f900-3421-11e9-8fe8-e610576bd510.png)

I'm in a corporate Azure and I don't have the permission to create a storageAccount (working on that).  So I create a batchAccount without it.  

When I run the tutorial in R with my batchAccount without a storageAccount, I get this error:
`Error in base64(txt, FALSE, mode) : 
  CHAR() can only be applied to a 'CHARSXP', not a 'NULL'`

From this issue [(link)](https://github.com/Azure/doAzureParallel/issues/293), I started to believe my bug was link to the missing storage account.  

Am I right?  Do `doAzureParallel` requires a storageAccount even if it's not needed to make a batachAccount?

**Comment by brnleehng** [comment]
Hi @BastienFR 

doAzureParallel requires a storageAccount for processing jobs. However, a storageAccount is not needed for creating a batchAccount via portal or through the AzureSMR package.

Thanks,
Brian
