### ISSUE TITLE
Merging with R 3.6

### ISSUE THREAD

**Issue by pmags** [Azure/doAzureParallel#355]
As a test i ran your caret example (code and cluster). While merging it returns the following error on stderr.txt:

running
  '/usr/lib/R/bin/R --slave --no-restore --no-save --no-environ --no-restore --no-site-file --file=/mnt/batch/tasks/workitems/job20190613075533/job-1/jobpreparation/wd/merger.R --args 10 10 stop'

Error in readRDS(paste0(batchJobPreparationDirectory, "/", batchJobId,  : 
  cannot read workspace version 3 written by R 3.6.0; need R 3.5.0 or newer
Execution halted

Downgrading to R 3.5.3 on my machine solved the problem and it merged without a problem. Bypassing the merge step and compiling locally does solve the problem too. But given that we would like to use the latest R version on our machine (using different R versions is easy on windows but not so friendly on mac on linux) is it possible for you to look into this issue ?

**Comment by brnleehng** [comment]
If you run these commands and restart your session,
devtools::install_github("Azure/rAzureBatch", ref="fix/v3.7-support")
devtools::install_github("Azure/doAzureParallel", ref="fix/v3.7-support")

Thanks,
Brian

**Comment by pmags** [comment]
Hi @brnleehng thank you for your answer. I haven't had the time to check the versions you suggest but i do plan to test it this week. 

Once i do it i give you feedback

Thanks
Pedro

**Comment by brnleehng** [comment]
I've updated doAzureParallel with the 3.6 support. 

```R
devtools::install_github("Azure/doAzureParallel", ref = "v0.8.0")
```
