### ISSUE TITLE
Allow merge task to run on task failures

### ISSUE THREAD

**Issue by paselem** [Azure/doAzureParallel#36]
Currently, if any tasks fail with a non-zero exit code, the job will get blocked by waiting for the merge task indefinitely. The for-loop should not get blocked but return an error on the job instead.

**Comment by grayskripko** [comment]
I believe it should be a bug with the highest priority. It requires a lot of Azure knowledge to understand why your first test pool does not return anything and is getting blocked

**Comment by paselem** [comment]
Completely agree. We are working to get 0.4.0 released now and will look at this soon after. We have had a bit of conversation around how to address this issue and we have agreed on the following rules:
1. By default, any failed tasks should fail a job (i.e. the for-each-loop) immediately and return
2. A user can optionally override this behavior (as part of the job options) and allow the job to continue on failures. The merge task will run regardless of failures.

Please let us know if you have any additional feedback on this.
Thanks,
-Pablo
