### ISSUE TITLE
getJobFile does not write a file even with downloadPath set

### ISSUE THREAD

**Issue by zerweck** [Azure/doAzureParallel#362]
The reason is that the write object is not passed to the AzureRequestV2 constructor. I have written a small quickfix in a PR in the rAzureBatch repo, but It does not seem very active so i am cross posting here. 

The PR:
Azure/rAzureBatch#70

**Comment by brnleehng** [comment]
Yes we mostly track issues via doAzureParallel for rAzureBatch
