### ISSUE TITLE
Batch pools using image with an imminent expiration date (batch.node.ubuntu 16.04)

### ISSUE THREAD

**Issue by d-sci** [Azure/doAzureParallel#375]
I get this warning in the Azure portal that my pool (created by doAzureParallel) is "using an image with an imminent expiration date". It appears this will be unsupported at the end of the month (2021-05-30).

![Screen Shot 2021-05-09 at 1 18 55 AM](https://user-images.githubusercontent.com/6467018/117561534-943ad080-b065-11eb-822b-296fdbd1f2f8.png)

Looks like this is set here - hoping this is an easy fix:

https://github.com/Azure/doAzureParallel/blob/56661a423351622dab4dbf85276ad256aff83e24/R/batch-api.R#L261-L270

**Comment by brnleehng** [comment]
Updating with this PR #378
