### ISSUE TITLE
RegisterPool gives an error

### ISSUE THREAD

**Issue by lmiroslaw** [Azure/doAzureParallel#4]
After filling up the config file with Batch credentials I run:

`pool <- registerPool("my_pool_config.json")`

and got an error:
No encoding supplied: defaulting to UTF-8.
[1] "Booting compute nodes. . . Please wait. . . There are currently no nodes in the pool. . ."
  |                                                                                                                |   0%
Error in if (x$state == "idle") { : argument is of length zero
>

**Comment by lmiroslaw** [comment]
I noticed the 'registerPool' uses pool$vmSize instead of pool$vmsize. Therefore it is always NULL. Maybe it matters.

**Comment by brnleehng** [comment]
We will be adding a config validator. It should be pool$vmSize however our docs has a typo. We'll fixed the config section of the doc.
