### ISSUE TITLE
Unfriendly error message when there are no jobs

### ISSUE THREAD

**Issue by RobertKomara** [Azure/doAzureParallel#49]
Hi! This is the current behavior when there are no jobs:

> getJobList()
[1] "Job List: "
Error in jobs$value[[j]] : subscript out of bounds

It would be much nicer to get something like this back as is returned in the Azure web interface:

No jobs were found for this Batch account

Thanks!

**Comment by paselem** [comment]
This has been addressed by #46

**Comment by RobertKomara** [comment]
I installed the latest and can confirm this works now, Thanks.
