### ISSUE TITLE
NAMESPACE problems

### ISSUE THREAD

**Issue by grayskripko** [Azure/doAzureParallel#71]
I was faced with lots of problems using your package in mine.
Please, read carefully http://r-pkgs.had.co.nz/namespace.html and use ```@import```, ```@importFrom``` and ```::``` for your functions.
The first problems are related to the ```rAzureBatch::addPool``` function (it is not in imported to namespace) and the ```httr::connect``` function in rAzureBatch (the same problem).
At the moment, I have to clutter up user search path using workarounds like ```attachNamespace('rAzureBatch')``` to help doAzureParallel to see rAzureBatch functions

**Comment by brnleehng** [comment]
Currently changing doAzureParallel's package to use `::`  for other packages while reformatting all the code. Will be added in our next milestone.

**Comment by brnleehng** [comment]
#72
