### ISSUE TITLE
Private repository packages

### ISSUE THREAD

**Issue by grayskripko** [Azure/doAzureParallel#73]
Package management question: Is it possible to install private github packages to my pool?

**Comment by dustindall** [comment]
Yes, when you create a cluster configuration template you can pass in your github authorization token (see image below). 

`generateClusterConfig("cluster.json")`

![image](https://user-images.githubusercontent.com/8218382/29566146-9caebf00-86fd-11e7-9daf-ce1679ec9138.png)

**Comment by grayskripko** [comment]
thank you very much!

**Comment by grayskripko** [comment]
@dustindall where can I find the full documentation to cluster.json file?

**Comment by dustindall** [comment]
This is new functionality to the generateClusterConfig template and the docs have not been updated.

Per the devtools::install_github "auth_token" instructions

> auth_token	
> To install from a private repo, generate a personal access token (PAT) in https://github.com/settings/tokens and supply to this argument. This is safer than using a password because you can easily delete a PAT without affecting any others. Defaults to the GITHUB_PAT environment variable.
 
You can delete the yellow brackets and paste in your personal access token.

**Comment by grayskripko** [comment]
this way "githubAuthenticationToken": "123abc123..." does not work. The command ```cluster <- makeCluster("cluster.json")``` does not return anything and has been freezing for 5 hours

**Comment by grayskripko** [comment]
I've found the reason. ```doAzureParallel::makeCluster``` has been masked by ```parallel``` package

**Comment by dustindall** [comment]
I had to go a through some iterations to get my packages to work. I thought it was easier to create an azure linux dsvm and install the required packages that I needed on my cluster. Doing this I ran into issues with the MRAN snapshot date for packages preinstalled on the dsvm. I also caught a couple of my own errors on my description file (import and remotes).

You should also check the logs. See the instructions from issue #43 on how to do this.

**Comment by dustindall** [comment]
Good to hear you find the issue.

**Comment by grayskripko** [comment]
it looks like everything works fine
