### ISSUE TITLE
Infinite "Waiting for tasks to complete. . ."

### ISSUE THREAD

**Issue by grayskripko** [Azure/doAzureParallel#76]
My ```%dopar%``` expression contains in the first line ```library(somePackage)``` with broken dependency. According to Azure node log, 
```ERROR: dependencies 'doAzureParallel', 'rAzureBatch' are not available for package 'stackatto'```.
Looks like I should not add both azure packages to DESCRIPTION Imports because it relies on cran availability.

Nevertheless, all nodes are in the state "Start task failed". 
```%dopar%``` is blocking R session without any result.

**Comment by brnleehng** [comment]
Hey Gray,

1) Your expression does not need to reference via `library(somePackage)`, .packages will do it for you

Example:
`foreach(i = 1:3, .packages = c("stackatto"))`, we will automatically set the library('stackatto') for you as syntactic sugar.

2) Is doAzureParallel and rAzureBatch in your cluster configuration file for github package installation?

3) I will add more logging statements such as start task failed in the `makeCluster` so users are aware that their nodes are not up and should not run a foreach statement. 

Thanks!
Brian

**Comment by grayskripko** [comment]
1. After reading your documentation I thought ```.packages``` argument is used as ```install.packages(stackatto)```, not as ```library(stackatto)```. Apparently, it is worth to clarify this distinction in the documentation.
2. No, it is not. It is in ```stackatto``` DESCRIPTION file using  [this approach](https://github.com/Azure/doAzureParallel/pull/77#pullrequestreview-58149424).
3. This is a good idea regarding logging but it may be more important to prevent infinite execution of any doAzureParallel functions.

Thank you, Brian.

**Comment by brnleehng** [comment]
This will be added to our next milestone 0.4.3 

Related-issue:
https://github.com/Azure/doAzureParallel/issues/36

Thanks Gray
