### ISSUE TITLE
Error in callStorageSas: Not Found (HTTP 404)

### ISSUE THREAD

**Issue by grayskripko** [Azure/doAzureParallel#78]
What could be the reason of
``` 
Waiting for tasks to complete. . .
  |================================================================================| 100%
Error in callStorageSas(request, args$accountName, sas_params = sasToken,  : 
  Not Found (HTTP 404).
```
How can I debug it?

**Comment by grayskripko** [comment]
the only node with an error is merge node. stderr.txt ends with:
```blobxfer: error: unrecognized arguments: result/job20170823162451-task2-result.rds result/job20170823162451-task3-result.rds result/job20170823162451-task4-result.rds result/job20170823162451-task5-result.rds result/job20170823162451-task6-result.rds
```

**Comment by grayskripko** [comment]
it could be memory allocation problems but merger logs do not contain such notes

**Comment by brnleehng** [comment]
#36 It looks like the tasks failed, but we use a try-catch on the worker script to force the merge task to run. But the merge task doesn't find the results of the other tasks. Planning a fix for this issue. 

Our current way of debugging is looking through the Azure portal for logs or if you have Azure Storage explorer,  which is not ideal (Will be a focus point in our upcoming milestones)

Log into the portal at portal.azure.com
Find your batch account and open it
Click on Jobs in the left navigation menu
Open your job
Select 'Tasks' in the left navigation menu
Select any task (Choose the task with "merge")
Select 'Files on nodes' in the left navigation menu
Look for stdout.txt, stderr.txt and task#-merge.txt.

Thanks

**Comment by grayskripko** [comment]
Nice to see I figured out how to use azure portal UI and how to get node's logs. 
Thank you, Brian, for your detailed explanation of each step.
I checked all 3 txt files and still getting the only one useful log chunk described above:
```blobxfer: error: unrecognized arguments...```
The problem does not appear when I use 4 jobs and is related to 6 and more jobs.
Is it memory allocation problem, what do you think?

**Comment by grayskripko** [comment]
I chose other nodes with more memory and it solved the problem. But I'm still wondering, is it possible to get an appropriate error message about memory allocation problem?

**Comment by brnleehng** [comment]
Yes, I will look into an appropriate error message about memory allocation problem. None the less, I'll add a summary statement in the task logs in the worker script. (Start time, end time, memory usage, CPU usage..) 

I'm surprised in the task# R log files didn't print out `Error: cannot allocate vector of size '130.4mb'` or  something along those lines. Did you see any logs containing those kind of error messages?

**Comment by grayskripko** [comment]
I met that error once in the merger node but not now.
I believe the problem is related to https://github.com/Azure/blobxfer and that tool was called in an inappropriate way, using wrong or shifted set of arguments. Maybe some ```blobxfer``` argument was NULL or something like that as a result of previous memory allocation problem. Anyway, the only node with error code != 0 is the merger node and I have investigated all its txt files.
What do you think, where should we create a bug report on this problem? In ```blobxfer``` repository?

**Comment by brnleehng** [comment]
- Do you have the entire error log files that I can view?
- Are the results 2 - 6 actually in storage? 

If the results are in storage, I think we should report a bug in blobxfer repository. Since the command we are using in blobxfer is using wildcard operator, `blobxfer %s %s %s --download --saskey $BLOBXFER_SASKEY --remoteresource . --include result/*.rds`

**Comment by grayskripko** [comment]
@brnleehng 
Sorry, can not reproduce it now. Getting correct error description
```
Error : cannot allocate vector of size 329.2 Mb
```
