### ISSUE TITLE
Node rebooting

### ISSUE THREAD

**Issue by grayskripko** [Azure/doAzureParallel#80]
Nodes can be broken on command ```doAzureParallel::makeCluster``` with the state "Start task failed". It looks like temporary internet problems. The error log on a broken node ends with
```
...
Downloading GitHub repo Azure/rAzureBatch@master
from URL https://api.github.com/repos/Azure/rAzureBatch/zipball/master
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Server returned nothing (no headers, no data)
Calls: <Anonymous> ... request_fetch -> request_fetch.write_memory -> <Anonymous> -> .Call
Execution halted
```

I found the way to get the list of broken nodes 
```
Filter(function(nd) nd$state == 'starttaskfailed', rAzureBatch::listPoolNodes('grayPool')$value)
```

How can I reboot broken nodes?
I believe it is worth to add such opportunity to ```doAzure::makeCluster``` as an optional argument.

**Comment by brnleehng** [comment]
Hey Gray,

I'll take a look into adding reboot option for nodes since our Azure Batch supports this operation (https://docs.microsoft.com/en-us/rest/api/batchservice/reboot-a-node)

Thanks

**Comment by brnleehng** [comment]
https://github.com/Azure/rAzureBatch/pull/31
