### ISSUE TITLE
Blob permissions when using resourceFiles

### ISSUE THREAD

**Issue by simon-tarr** [Azure/doAzureParallel#82]
The default blob container permissions are set to "Private (No anonymous access)". With this default setting, makeCluster() will error when using the argument resourceFiles with the message:

> Warning message:
In waitForNodesToComplete(pool$id, 60000) :
  The following 1 nodes failed while running the start task:

Container permissions must be set to "Blob (Anonymous read access for blobs only)" for the pool to be provisioned correctly. It took me some time this afternoon to troubleshoot this issue. This can be avoided with a line in the documentation to make users aware of the default. 

(For reference I am referring to this documentation:
https://github.com/Azure/doAzureParallel/blob/master/docs/21-distributing-data.md
https://github.com/Azure/doAzureParallel/blob/master/samples/resource_files_example.R)

**Comment by brnleehng** [comment]
Thanks Simon, will update the documentation for more clarity
